//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        
        public int commentId { get; set; }
        [DisplayName("Comment")]
        [Required(ErrorMessage = "Comment is Required")]
        
        public string commentText { get; set; }
        public Nullable<int> commentedBy { get; set; }
        public Nullable<int> postId { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
    }
}
