//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int lId { get; set; }
        public string vote { get; set; }
        public Nullable<int> likedBy { get; set; }
        public Nullable<int> postId { get; set; }
        public Nullable<System.DateTime> likedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
