//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Logs
    {
        public int Id { get; set; }

        [Display(Name = "Logged In user")]
        public int userId { get; set; }

        [Display(Name = "Logged In Time")]
        public System.DateTime loggedTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
