//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int rId { get; set; }
        public int postId { get; set; }
        public string reason { get; set; }
        public Nullable<int> reportedBy { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
