//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string HomeImage { get; set; }
        public string HomeImageText { get; set; }
        public Nullable<int> NumberOfLastPost { get; set; }
        public Nullable<int> NumberOfCategory { get; set; }
        public Nullable<int> PostNumberInPage { get; set; }
        public Nullable<int> NumberOfTopPost { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
