//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int id { get; set; }
        public string homeImage { get; set; }
        public string homeImageText { get; set; }
        public Nullable<int> numberOfLastPost { get; set; }
        public Nullable<int> numberOfCategory { get; set; }
        public Nullable<int> postNumberInPage { get; set; }
        public Nullable<int> numberOfTopPost { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
