//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Category = new HashSet<Category>();
            this.Comment = new HashSet<Comment>();
            this.Like = new HashSet<Like>();
            this.Logs = new HashSet<Logs>();
            this.Post = new HashSet<Post>();
            this.Reports = new HashSet<Reports>();
            this.Setting = new HashSet<Setting>();
        }
        [Key]
        [DisplayName("User ID")]
        public int userId { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name is Required")]
        [StringLength(100, MinimumLength = 2)]
        public string firstName { get; set; }


        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name is Required")]
        [StringLength(100, MinimumLength = 2)]
        public string lastName { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is Required")]
        [Index(IsUnique = true)]
        [RegularExpression("^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$", ErrorMessage = "Must be a valid email")]
        public string username { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is Required")]
        [StringLength(100, MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Create Time")]
        public Nullable<System.DateTime> createTime { get; set; }
        [DisplayName("Updated Time")]
        public Nullable<System.DateTime> updateTime { get; set; }
        [DisplayName("Last Logged in")]
        public Nullable<System.DateTime> lastLogin { get; set; }
        [DisplayName("Role")]
        public Nullable<int> userType { get; set; }

        [Required(ErrorMessage = "Security Question is Required")]
        [DisplayName("Security Question")]
        public Nullable<int> questionId { get; set; }

        [DisplayName("Answer")]
        [Required(ErrorMessage = "Answer is Required")]
        [StringLength(50, MinimumLength = 2)]
        public string answer { get; set; }

        [DisplayName("Profile Image")]
        public string userImage { get; set; }
        public Nullable<double> imageSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Like { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
        public virtual Role Role { get; set; }

        virtual public IEnumerable<Role> IENUMRoleDetails { get; set; }

        public virtual SecurityQuestion SecurityQuestion { get; set; }
        virtual public IEnumerable<SecurityQuestion> IENUMQuestionDetails { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setting> Setting { get; set; }
    }
}
